name: Reproducible paper build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: TeXLive
      run: |
        # This "full" takes forever to install, but trying to install packages
        # with tlmgr on a github CI machine is like being in the movie Brazil.
        sudo apt install texlive-full

    - name: Conda
      uses: conda-incubator/setup-miniconda@v2.0.0
      with:
        environment-file: environment.yml
        activate-environment: reproducible

    - name: Build
      shell: bash -l {0}
      run: |
        make build/reproducible.pdf
        make abridged_build/reproducible.pdf
