name: Reproducible paper build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: scheme-basic xetex fontspec underscore latexmk booktabs etoolbox

    - name: Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        activate-environment: reproducible

    - name: Build
      shell: bash -l {0}
      run: |
        make build/reproducible.pdf
        make abridged_build/reproducible.pdf
